services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
